import React from 'react';
import { StaticImage } from "gatsby-plugin-image";

export const puppy1  = ({ moreSx }) => <StaticImage alt='placeholder' src='./1.jpg' sx={moreSx} />;
export const puppy2  = ({ moreSx }) => <StaticImage alt='placeholder' src='./2.jpg' sx={moreSx} />;
export const puppy3  = ({ moreSx }) => <StaticImage alt='placeholder' src='./3.jpg' sx={moreSx} />;
export const puppy4  = ({ moreSx }) => <StaticImage alt='placeholder' src='./4.jpg' sx={moreSx} />;
export const puppy5  = ({ moreSx }) => <StaticImage alt='placeholder' src='./5.jpg' sx={moreSx} />;
export const puppy6  = ({ moreSx }) => <StaticImage alt='placeholder' src='./6.jpg' sx={moreSx} />;
export const puppy7  = ({ moreSx }) => <StaticImage alt='placeholder' src='./7.jpg' sx={moreSx} />;
export const puppy8  = ({ moreSx }) => <StaticImage alt='placeholder' src='./8.jpg' sx={moreSx} />;
export const puppy9  = ({ moreSx }) => <StaticImage alt='placeholder' src='./9.jpg' sx={moreSx} />;
export const puppy10 = ({ moreSx }) => <StaticImage alt='placeholder' src='./10.jpg' sx={moreSx} />;
export const puppy11 = ({ moreSx }) => <StaticImage alt='placeholder' src='./11.jpg' sx={moreSx} />;
export const puppy12 = ({ moreSx }) => <StaticImage alt='placeholder' src='./12.jpg' sx={moreSx} />;
export const puppy13 = ({ moreSx }) => <StaticImage alt='placeholder' src='./13.jpg' sx={moreSx} />;
export const puppy14 = ({ moreSx }) => <StaticImage alt='placeholder' src='./14.jpg' sx={moreSx} />;
export const puppy15 = ({ moreSx }) => <StaticImage alt='placeholder' src='./15.jpg' sx={moreSx} />;
export const puppy16 = ({ moreSx }) => <StaticImage alt='placeholder' src='./16.jpg' sx={moreSx} />;
export const puppy17 = ({ moreSx }) => <StaticImage alt='placeholder' src='./17.jpg' sx={moreSx} />;
export const puppy18 = ({ moreSx }) => <StaticImage alt='placeholder' src='./18.jpg' sx={moreSx} />;
export const puppy19 = ({ moreSx }) => <StaticImage alt='placeholder' src='./19.jpg' sx={moreSx} />;
export const puppy20 = ({ moreSx }) => <StaticImage alt='placeholder' src='./20.jpg' sx={moreSx} />;
export const puppy21 = ({ moreSx }) => <StaticImage alt='placeholder' src='./21.jpg' sx={moreSx} />;
export const puppy22 = ({ moreSx }) => <StaticImage alt='placeholder' src='./22.jpg' sx={moreSx} />;
export const puppy23 = ({ moreSx }) => <StaticImage alt='placeholder' src='./23.jpg' sx={moreSx} />;
export const puppy24 = ({ moreSx }) => <StaticImage alt='placeholder' src='./24.jpg' sx={moreSx} />;
export const puppy25 = ({ moreSx }) => <StaticImage alt='placeholder' src='./25.jpg' sx={moreSx} />;
export const puppy26 = ({ moreSx }) => <StaticImage alt='placeholder' src='./26.jpg' sx={moreSx} />;
export const puppy27 = ({ moreSx }) => <StaticImage alt='placeholder' src='./27.jpg' sx={moreSx} />;
export const puppy28 = ({ moreSx }) => <StaticImage alt='placeholder' src='./28.jpg' sx={moreSx} />;
