import React from 'react';
import { StaticImage } from "gatsby-plugin-image";

export const puppy1  = props => <StaticImage alt='placeholder' src='./1.jpg' {...props} />;
export const puppy2  = props => <StaticImage alt='placeholder' src='./2.jpg' {...props} />;
export const puppy3  = props => <StaticImage alt='placeholder' src='./3.jpg' {...props} />;
export const puppy4  = props => <StaticImage alt='placeholder' src='./4.jpg' {...props} />;
export const puppy5  = props => <StaticImage alt='placeholder' src='./5.jpg' {...props} />;
export const puppy6  = props => <StaticImage alt='placeholder' src='./6.jpg' {...props} />;
export const puppy7  = props => <StaticImage alt='placeholder' src='./7.jpg' {...props} />;
export const puppy8  = props => <StaticImage alt='placeholder' src='./8.jpg' {...props} />;
export const puppy9  = props => <StaticImage alt='placeholder' src='./9.jpg' {...props} />;
export const puppy10 = props => <StaticImage alt='placeholder' src='./10.jpg' {...props} />;
export const puppy11 = props => <StaticImage alt='placeholder' src='./11.jpg' {...props} />;
export const puppy12 = props => <StaticImage alt='placeholder' src='./12.jpg' {...props} />;
export const puppy13 = props => <StaticImage alt='placeholder' src='./13.jpg' {...props} />;
export const puppy14 = props => <StaticImage alt='placeholder' src='./14.jpg' {...props} />;
export const puppy15 = props => <StaticImage alt='placeholder' src='./15.jpg' {...props} />;
export const puppy16 = props => <StaticImage alt='placeholder' src='./16.jpg' {...props} />;
export const puppy17 = props => <StaticImage alt='placeholder' src='./17.jpg' {...props} />;
export const puppy18 = props => <StaticImage alt='placeholder' src='./18.jpg' {...props} />;
export const puppy19 = props => <StaticImage alt='placeholder' src='./19.jpg' {...props} />;
export const puppy20 = props => <StaticImage alt='placeholder' src='./20.jpg' {...props} />;
export const puppy21 = props => <StaticImage alt='placeholder' src='./21.jpg' {...props} />;
export const puppy22 = props => <StaticImage alt='placeholder' src='./22.jpg' {...props} />;
export const puppy23 = props => <StaticImage alt='placeholder' src='./23.jpg' {...props} />;
export const puppy24 = props => <StaticImage alt='placeholder' src='./24.jpg' {...props} />;
export const puppy25 = props => <StaticImage alt='placeholder' src='./25.jpg' {...props} />;
export const puppy26 = props => <StaticImage alt='placeholder' src='./26.jpg' {...props} />;
export const puppy27 = props => <StaticImage alt='placeholder' src='./27.jpg' {...props} />;
export const puppy28 = props => <StaticImage alt='placeholder' src='./28.jpg' {...props} />;
