import React from 'react';
import { StaticImage } from "gatsby-plugin-image";

export const puppy1  = ({ className = '' }) => <StaticImage alt='placeholder' src='./1.jpg' className={className} />;
export const puppy2  = ({ className = '' }) => <StaticImage alt='placeholder' src='./2.jpg' className={className} />;
export const puppy3  = ({ className = '' }) => <StaticImage alt='placeholder' src='./3.jpg' className={className} />;
export const puppy4  = ({ className = '' }) => <StaticImage alt='placeholder' src='./4.jpg' className={className} />;
export const puppy5  = ({ className = '' }) => <StaticImage alt='placeholder' src='./5.jpg' className={className} />;
export const puppy6  = ({ className = '' }) => <StaticImage alt='placeholder' src='./6.jpg' className={className} />;
export const puppy7  = ({ className = '' }) => <StaticImage alt='placeholder' src='./7.jpg' className={className} />;
export const puppy8  = ({ className = '' }) => <StaticImage alt='placeholder' src='./8.jpg' className={className} />;
export const puppy9  = ({ className = '' }) => <StaticImage alt='placeholder' src='./9.jpg' className={className} />;
export const puppy10 = ({ className = '' }) => <StaticImage alt='placeholder' src='./10.jpg' className={className} />;
export const puppy11 = ({ className = '' }) => <StaticImage alt='placeholder' src='./11.jpg' className={className} />;
export const puppy12 = ({ className = '' }) => <StaticImage alt='placeholder' src='./12.jpg' className={className} />;
export const puppy13 = ({ className = '' }) => <StaticImage alt='placeholder' src='./13.jpg' className={className} />;
export const puppy14 = ({ className = '' }) => <StaticImage alt='placeholder' src='./14.jpg' className={className} />;
export const puppy15 = ({ className = '' }) => <StaticImage alt='placeholder' src='./15.jpg' className={className} />;
export const puppy16 = ({ className = '' }) => <StaticImage alt='placeholder' src='./16.jpg' className={className} />;
export const puppy17 = ({ className = '' }) => <StaticImage alt='placeholder' src='./17.jpg' className={className} />;
export const puppy18 = ({ className = '' }) => <StaticImage alt='placeholder' src='./18.jpg' className={className} />;
export const puppy19 = ({ className = '' }) => <StaticImage alt='placeholder' src='./19.jpg' className={className} />;
export const puppy20 = ({ className = '' }) => <StaticImage alt='placeholder' src='./20.jpg' className={className} />;
export const puppy21 = ({ className = '' }) => <StaticImage alt='placeholder' src='./21.jpg' className={className} />;
export const puppy22 = ({ className = '' }) => <StaticImage alt='placeholder' src='./22.jpg' className={className} />;
export const puppy23 = ({ className = '' }) => <StaticImage alt='placeholder' src='./23.jpg' className={className} />;
export const puppy24 = ({ className = '' }) => <StaticImage alt='placeholder' src='./24.jpg' className={className} />;
export const puppy25 = ({ className = '' }) => <StaticImage alt='placeholder' src='./25.jpg' className={className} />;
export const puppy26 = ({ className = '' }) => <StaticImage alt='placeholder' src='./26.jpg' className={className} />;
export const puppy27 = ({ className = '' }) => <StaticImage alt='placeholder' src='./27.jpg' className={className} />;
export const puppy28 = ({ className = '' }) => <StaticImage alt='placeholder' src='./28.jpg' className={className} />;
